name: Deploy react Project

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Trigger Deployment
      run: |
        curl -X POST http://127.0.0.1:3000/deploy
